//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sklad
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [BusinessServer("IIS.Sklad.ЗаказБС, Sklad.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private System.DateTime fДатаЗаполнения = System.DateTime.UtcNow;
        
        private IIS.Sklad.СостояниеЗаказа fСтатус;
        
        private System.DateTime fДатаОтгрузки;
        
        private System.DateTime? fДатаОплаты;
        
        private decimal fЦена;
        
        private IIS.Sklad.Клиент fКлиент;
        
        private IIS.Sklad.Регион fРегион;
        
        private IIS.Sklad.DetailArrayOfСтрокаЗаказа fСтрокаЗаказа;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Номер CustomAttributes)

        // *** End programmer edit section *** (Заказ.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Номер Get start)

                // *** End programmer edit section *** (Заказ.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Заказ.Номер Get end)

                // *** End programmer edit section *** (Заказ.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Номер Set start)

                // *** End programmer edit section *** (Заказ.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Заказ.Номер Set end)

                // *** End programmer edit section *** (Заказ.Номер Set end)
            }
        }
        
        /// <summary>
        /// ДатаЗаполнения.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаЗаполнения CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаЗаполнения CustomAttributes)
        public virtual System.DateTime ДатаЗаполнения
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаЗаполнения Get start)

                // *** End programmer edit section *** (Заказ.ДатаЗаполнения Get start)
                System.DateTime result = this.fДатаЗаполнения;
                // *** Start programmer edit section *** (Заказ.ДатаЗаполнения Get end)

                // *** End programmer edit section *** (Заказ.ДатаЗаполнения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаЗаполнения Set start)

                // *** End programmer edit section *** (Заказ.ДатаЗаполнения Set start)
                this.fДатаЗаполнения = value;
                // *** Start programmer edit section *** (Заказ.ДатаЗаполнения Set end)

                // *** End programmer edit section *** (Заказ.ДатаЗаполнения Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Статус CustomAttributes)

        // *** End programmer edit section *** (Заказ.Статус CustomAttributes)
        public virtual IIS.Sklad.СостояниеЗаказа Статус
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Статус Get start)

                // *** End programmer edit section *** (Заказ.Статус Get start)
                IIS.Sklad.СостояниеЗаказа result = this.fСтатус;
                // *** Start programmer edit section *** (Заказ.Статус Get end)

                // *** End programmer edit section *** (Заказ.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Статус Set start)

                // *** End programmer edit section *** (Заказ.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Заказ.Статус Set end)

                // *** End programmer edit section *** (Заказ.Статус Set end)
            }
        }
        
        /// <summary>
        /// ДатаОтгрузки.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаОтгрузки CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаОтгрузки CustomAttributes)
        public virtual System.DateTime ДатаОтгрузки
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Get start)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Get start)
                System.DateTime result = this.fДатаОтгрузки;
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Get end)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Set start)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Set start)
                this.fДатаОтгрузки = value;
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Set end)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Set end)
            }
        }
        
        /// <summary>
        /// ДатаОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаОплаты CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаОплаты CustomAttributes)
        public virtual System.DateTime? ДатаОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Get start)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Get start)
                System.DateTime? result = this.fДатаОплаты;
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Get end)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Set start)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Set start)
                this.fДатаОплаты = value;
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Set end)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Цена CustomAttributes)

        // *** End programmer edit section *** (Заказ.Цена CustomAttributes)
        public virtual decimal Цена
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Цена Get start)

                // *** End programmer edit section *** (Заказ.Цена Get start)
                decimal result = this.fЦена;
                // *** Start programmer edit section *** (Заказ.Цена Get end)

                // *** End programmer edit section *** (Заказ.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Цена Set start)

                // *** End programmer edit section *** (Заказ.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Заказ.Цена Set end)

                // *** End programmer edit section *** (Заказ.Цена Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Клиент CustomAttributes)

        // *** End programmer edit section *** (Заказ.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Sklad.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Клиент Get start)

                // *** End programmer edit section *** (Заказ.Клиент Get start)
                IIS.Sklad.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Заказ.Клиент Get end)

                // *** End programmer edit section *** (Заказ.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Клиент Set start)

                // *** End programmer edit section *** (Заказ.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Заказ.Клиент Set end)

                // *** End programmer edit section *** (Заказ.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Регион CustomAttributes)

        // *** End programmer edit section *** (Заказ.Регион CustomAttributes)
        [PropertyStorage(new string[] {
                "Регион"})]
        [NotNull()]
        public virtual IIS.Sklad.Регион Регион
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Регион Get start)

                // *** End programmer edit section *** (Заказ.Регион Get start)
                IIS.Sklad.Регион result = this.fРегион;
                // *** Start programmer edit section *** (Заказ.Регион Get end)

                // *** End programmer edit section *** (Заказ.Регион Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Регион Set start)

                // *** End programmer edit section *** (Заказ.Регион Set start)
                this.fРегион = value;
                // *** Start programmer edit section *** (Заказ.Регион Set end)

                // *** End programmer edit section *** (Заказ.Регион Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.СтрокаЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.СтрокаЗаказа CustomAttributes)
        public virtual IIS.Sklad.DetailArrayOfСтрокаЗаказа СтрокаЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Get start)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Get start)
                if ((this.fСтрокаЗаказа == null))
                {
                    this.fСтрокаЗаказа = new IIS.Sklad.DetailArrayOfСтрокаЗаказа(this);
                }
                IIS.Sklad.DetailArrayOfСтрокаЗаказа result = this.fСтрокаЗаказа;
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Get end)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Set start)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Set start)
                this.fСтрокаЗаказа = value;
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Set end)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Set end)
            }
        }
    }
}
