//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sklad
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Клиент : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Наименование CustomAttributes)

        // *** End programmer edit section *** (Клиент.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Наименование Get start)

                // *** End programmer edit section *** (Клиент.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Клиент.Наименование Get end)

                // *** End programmer edit section *** (Клиент.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Наименование Set start)

                // *** End programmer edit section *** (Клиент.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Клиент.Наименование Set end)

                // *** End programmer edit section *** (Клиент.Наименование Set end)
            }
        }
    }
}
