//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sklad
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Строка заказа.
    /// </summary>
    // *** Start programmer edit section *** (СтрокаЗаказа CustomAttributes)

    // *** End programmer edit section *** (СтрокаЗаказа CustomAttributes)
    [BusinessServer("IIS.Sklad.ЗаказБС, Sklad.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [Caption("Строка заказа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class СтрокаЗаказа : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private decimal fЦенаСНалогами;
        
        private decimal fСумма;
        
        private IIS.Sklad.Товар fТовар;
        
        private IIS.Sklad.Заказ fЗаказ;
        
        // *** Start programmer edit section *** (СтрокаЗаказа CustomMembers)

        // *** End programmer edit section *** (СтрокаЗаказа CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаЗаказа.Количество CustomAttributes)

        // *** End programmer edit section *** (СтрокаЗаказа.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Количество Get start)

                // *** End programmer edit section *** (СтрокаЗаказа.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (СтрокаЗаказа.Количество Get end)

                // *** End programmer edit section *** (СтрокаЗаказа.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Количество Set start)

                // *** End programmer edit section *** (СтрокаЗаказа.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (СтрокаЗаказа.Количество Set end)

                // *** End programmer edit section *** (СтрокаЗаказа.Количество Set end)
            }
        }
        
        /// <summary>
        /// ЦенаСНалогами.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаЗаказа.ЦенаСНалогами CustomAttributes)

        // *** End programmer edit section *** (СтрокаЗаказа.ЦенаСНалогами CustomAttributes)
        public virtual decimal ЦенаСНалогами
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.ЦенаСНалогами Get start)

                // *** End programmer edit section *** (СтрокаЗаказа.ЦенаСНалогами Get start)
                decimal result = this.fЦенаСНалогами;
                // *** Start programmer edit section *** (СтрокаЗаказа.ЦенаСНалогами Get end)

                // *** End programmer edit section *** (СтрокаЗаказа.ЦенаСНалогами Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.ЦенаСНалогами Set start)

                // *** End programmer edit section *** (СтрокаЗаказа.ЦенаСНалогами Set start)
                this.fЦенаСНалогами = value;
                // *** Start programmer edit section *** (СтрокаЗаказа.ЦенаСНалогами Set end)

                // *** End programmer edit section *** (СтрокаЗаказа.ЦенаСНалогами Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаЗаказа.Сумма CustomAttributes)

        // *** End programmer edit section *** (СтрокаЗаказа.Сумма CustomAttributes)
        public virtual decimal Сумма
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Сумма Get start)

                // *** End programmer edit section *** (СтрокаЗаказа.Сумма Get start)
                decimal result = this.fСумма;
                // *** Start programmer edit section *** (СтрокаЗаказа.Сумма Get end)

                // *** End programmer edit section *** (СтрокаЗаказа.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Сумма Set start)

                // *** End programmer edit section *** (СтрокаЗаказа.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (СтрокаЗаказа.Сумма Set end)

                // *** End programmer edit section *** (СтрокаЗаказа.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Строка заказа.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаЗаказа.Товар CustomAttributes)

        // *** End programmer edit section *** (СтрокаЗаказа.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.Sklad.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Товар Get start)

                // *** End programmer edit section *** (СтрокаЗаказа.Товар Get start)
                IIS.Sklad.Товар result = this.fТовар;
                // *** Start programmer edit section *** (СтрокаЗаказа.Товар Get end)

                // *** End programmer edit section *** (СтрокаЗаказа.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Товар Set start)

                // *** End programmer edit section *** (СтрокаЗаказа.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (СтрокаЗаказа.Товар Set end)

                // *** End programmer edit section *** (СтрокаЗаказа.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Sklad.Заказ.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаЗаказа.Заказ CustomAttributes)

        // *** End programmer edit section *** (СтрокаЗаказа.Заказ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Заказ"})]
        public virtual IIS.Sklad.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Заказ Get start)

                // *** End programmer edit section *** (СтрокаЗаказа.Заказ Get start)
                IIS.Sklad.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (СтрокаЗаказа.Заказ Get end)

                // *** End programmer edit section *** (СтрокаЗаказа.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Заказ Set start)

                // *** End programmer edit section *** (СтрокаЗаказа.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (СтрокаЗаказа.Заказ Set end)

                // *** End programmer edit section *** (СтрокаЗаказа.Заказ Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of СтрокаЗаказа.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСтрокаЗаказа CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСтрокаЗаказа CustomAttributes)
    public class DetailArrayOfСтрокаЗаказа : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Sklad.DetailArrayOfСтрокаЗаказа members)

        // *** End programmer edit section *** (IIS.Sklad.DetailArrayOfСтрокаЗаказа members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СтрокаЗаказа by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СтрокаЗаказа.
        /// </summary>
        public DetailArrayOfСтрокаЗаказа(IIS.Sklad.Заказ fЗаказ) : 
                base(typeof(СтрокаЗаказа), ((ICSSoft.STORMNET.DataObject)(fЗаказ)))
        {
        }
        
        public IIS.Sklad.СтрокаЗаказа this[int index]
        {
            get
            {
                return ((IIS.Sklad.СтрокаЗаказа)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Sklad.СтрокаЗаказа dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
