//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sklad
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    // *** Start programmer edit section *** (Товар CustomAttributes)

    // *** End programmer edit section *** (Товар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Товар : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодТовара;
        
        private string fНазвание;
        
        private string fЕдиницаИзмерения;
        
        private string fОписание;
        
        private decimal fЦена;
        
        private string fКодКатегории;
        
        // *** Start programmer edit section *** (Товар CustomMembers)

        // *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// КодТовара.
        /// </summary>
        // *** Start programmer edit section *** (Товар.КодТовара CustomAttributes)

        // *** End programmer edit section *** (Товар.КодТовара CustomAttributes)
        public virtual int КодТовара
        {
            get
            {
                // *** Start programmer edit section *** (Товар.КодТовара Get start)

                // *** End programmer edit section *** (Товар.КодТовара Get start)
                int result = this.fКодТовара;
                // *** Start programmer edit section *** (Товар.КодТовара Get end)

                // *** End programmer edit section *** (Товар.КодТовара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.КодТовара Set start)

                // *** End programmer edit section *** (Товар.КодТовара Set start)
                this.fКодТовара = value;
                // *** Start programmer edit section *** (Товар.КодТовара Set end)

                // *** End programmer edit section *** (Товар.КодТовара Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Название CustomAttributes)

        // *** End programmer edit section *** (Товар.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Название Get start)

                // *** End programmer edit section *** (Товар.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Товар.Название Get end)

                // *** End programmer edit section *** (Товар.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Название Set start)

                // *** End programmer edit section *** (Товар.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Товар.Название Set end)

                // *** End programmer edit section *** (Товар.Название Set end)
            }
        }
        
        /// <summary>
        /// ЕдиницаИзмерения.
        /// </summary>
        // *** Start programmer edit section *** (Товар.ЕдиницаИзмерения CustomAttributes)

        // *** End programmer edit section *** (Товар.ЕдиницаИзмерения CustomAttributes)
        [StrLen(255)]
        public virtual string ЕдиницаИзмерения
        {
            get
            {
                // *** Start programmer edit section *** (Товар.ЕдиницаИзмерения Get start)

                // *** End programmer edit section *** (Товар.ЕдиницаИзмерения Get start)
                string result = this.fЕдиницаИзмерения;
                // *** Start programmer edit section *** (Товар.ЕдиницаИзмерения Get end)

                // *** End programmer edit section *** (Товар.ЕдиницаИзмерения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.ЕдиницаИзмерения Set start)

                // *** End programmer edit section *** (Товар.ЕдиницаИзмерения Set start)
                this.fЕдиницаИзмерения = value;
                // *** Start programmer edit section *** (Товар.ЕдиницаИзмерения Set end)

                // *** End programmer edit section *** (Товар.ЕдиницаИзмерения Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Описание CustomAttributes)

        // *** End programmer edit section *** (Товар.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Описание Get start)

                // *** End programmer edit section *** (Товар.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (Товар.Описание Get end)

                // *** End programmer edit section *** (Товар.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Описание Set start)

                // *** End programmer edit section *** (Товар.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (Товар.Описание Set end)

                // *** End programmer edit section *** (Товар.Описание Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Цена CustomAttributes)

        // *** End programmer edit section *** (Товар.Цена CustomAttributes)
        public virtual decimal Цена
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Цена Get start)

                // *** End programmer edit section *** (Товар.Цена Get start)
                decimal result = this.fЦена;
                // *** Start programmer edit section *** (Товар.Цена Get end)

                // *** End programmer edit section *** (Товар.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Цена Set start)

                // *** End programmer edit section *** (Товар.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Товар.Цена Set end)

                // *** End programmer edit section *** (Товар.Цена Set end)
            }
        }
        
        /// <summary>
        /// КодКатегории.
        /// </summary>
        // *** Start programmer edit section *** (Товар.КодКатегории CustomAttributes)

        // *** End programmer edit section *** (Товар.КодКатегории CustomAttributes)
        [StrLen(255)]
        public virtual string КодКатегории
        {
            get
            {
                // *** Start programmer edit section *** (Товар.КодКатегории Get start)

                // *** End programmer edit section *** (Товар.КодКатегории Get start)
                string result = this.fКодКатегории;
                // *** Start programmer edit section *** (Товар.КодКатегории Get end)

                // *** End programmer edit section *** (Товар.КодКатегории Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.КодКатегории Set start)

                // *** End programmer edit section *** (Товар.КодКатегории Set start)
                this.fКодКатегории = value;
                // *** Start programmer edit section *** (Товар.КодКатегории Set end)

                // *** End programmer edit section *** (Товар.КодКатегории Set end)
            }
        }
    }
}
